---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zj.
--- DateTime: 2021/6/3 0:03
---
print("hello")
print(os.getenv("USERNAME"))
print(os.date())
function say(a,b)
    if a > b then
        return a
    else
        return b
    end
end

local rus = say(5, 6)
print(rus)

--Config = {h="haha",a="lala"}
--Config.word = "lua"
--Config["name"]="hello lua"
--print(Config.word)
--print(Config.a)
--print(Config.name)
--arr = {1,2,3,4,5,"a","b"}
--for key,val in pairs(arr) do
--    print(key,val)
--end
print("haha".."wuwu") -- ..用于字符串拼接
print("19"+"11"+12) -- +会将两边转换为数值型进行计算
print("ha".."ww")
local stu = "sdeii"
print(#stu) -- #用于获取字节的长度
print(stu)

Person = {}
function Person:getName(name)
    print("我的名字是"..name)
end
Person:getName("zhangsan")